pg:
  adapter: postgresql
  username: postgres
  database: acts_as_ordered_tree_test
  host: 127.0.0.1
  encoding: unicode
  min_messages: ERROR
mysql:
  adapter: mysql2
  database: acts_as_ordered_tree_test
  username: root
  password:
  encoding: utf8
sqlite3:
  adapter: sqlite3
  database: acts_as_ordered_tree.sqlite3.db